# Generated by Django 4.2.1 on 2023-06-20 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='token',
            field=models.CharField(max_length=16, null=True, unique=True),
        ),
    ]
