# Generated by Django 4.2.2 on 2023-06-27 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productvariantproperties_value'),
        ('users', '0002_user_is_verified_userprofile_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.IntegerField()),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seller_inventory', to='products.productvariants')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seller_inventory', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
