# Generated by Django 4.2.2 on 2023-07-13 06:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_sellerinventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('house_no', models.CharField(default=120, max_length=20)),
                ('street', models.CharField(default='st 1220.', max_length=30)),
                ('city', models.CharField(default='bhiwani', max_length=50)),
                ('state', models.CharField(default='haryana', max_length=40)),
                ('postal_code', models.CharField(default=127028, max_length=40)),
                ('detail_address', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='address', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
