# Generated by Django 4.2.2 on 2023-07-13 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_userprofile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(default='users/profile_images/default.jpeg', upload_to='users/profile_images'),
        ),
    ]
