# Generated by Django 4.1 on 2023-08-02 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_userprofile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
