# Generated by Django 4.2.2 on 2023-07-11 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_userwishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorders',
            name='payment_status',
            field=models.CharField(default='Paid', max_length=50),
        ),
    ]
