# Generated by Django 4.2.2 on 2023-07-13 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_useraddress'),
        ('orders', '0003_userorders_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorders',
            name='address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='users.useraddress'),
        ),
    ]
