# Generated by Django 4.2.2 on 2023-07-17 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_userorders_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorderitems',
            name='status',
            field=models.CharField(default='placed', max_length=100),
        ),
    ]
