# Generated by Django 4.2.2 on 2023-07-17 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_userorderitems_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorders',
            name='status',
            field=models.CharField(default='placed', max_length=100),
        ),
    ]
