# Generated by Django 4.2.1 on 2023-06-21 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_properties_productvariants_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ImageField(default=None, upload_to='products/products'),
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='properties',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
