# Generated by Django 4.2.1 on 2023-06-22 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_products_image_alter_products_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariants',
            name='code',
            field=models.CharField(default='123', max_length=30, unique=True),
        ),
    ]
