# Generated by Django 4.2.1 on 2023-06-22 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_productvariants_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariantproperties',
            name='value',
            field=models.CharField(default='red', max_length=30),
        ),
    ]
