# Generated by Django 4.2.2 on 2023-06-29 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productvariantproperties_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariants',
            name='is_master',
            field=models.BooleanField(default=False),
        ),
    ]
