# Generated by Django 4.2.2 on 2023-07-04 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productvariants_is_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='brands',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='categories',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productvariants',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
