# Generated by Django 4.2.2 on 2023-07-27 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_brands_is_active_categories_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
